processes:
  api:
    command: uv run manage.py runserver 2948
    working_dir: api
    environment:
    - DJANGO_DEBUG=True
  docs:
    command: make livehtml
    working_dir: docs
  frontend:
    command: yarn && yarn dev
    working_dir: frontend
  glove:
    command: pio run -e debug -t upload -t monitor
    working_dir: glove
    disabled: true # requires ESP32
