excludes = ['*/.gitignore', '.gitignore', 'flake.lock']

[formatter.c]
command = 'clang-format'
options = ['-i']
includes = ['*.[ch]', '*.[ch]pp']

[formatter.cmake]
command = 'cmake-format'
options = ['-i']
includes = ['CMakeLists.txt', '*/CMakeLists.txt']

[formatter.nix]
command = 'nixpkgs-fmt'
includes = ['*.nix']

[formatter.shfmt]
command = 'shfmt'
options = ['-w', '-s']
includes = ['*.sh', '.envrc']

[formatter.taplo]
command = 'taplo'
options = ['fmt']
includes = ['*.toml']

[formatter.yamlfmt]
command = 'yamlfmt'
includes = ['*.yml', '*.yaml', '.clang-format']
