@startwbs

skinparam dpi 300

* Project Integration
** Electrical
*** Power Supply
*** PCB
** Mechanical
*** Sensor
*** Motor
*** Glove
** Software
*** Tremor suppression algorithm\n<size:8>e.g. PID Control, Control loop</size>
*** Database
**** Entity-Relationship Diagram
**** SQL Queries
*** Web app
**** Backend
**** Frontend
*** Networking
**** Server Setup
**** Encryption\n<size:8>e.g. HTTPS</size>
**** WiFi on ESP32

@endwbs
