[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "daphne>=4.2.0",
  "django>=5.2.1",
  "gunicorn>=23.0.0",
  "uvicorn>=0.34.2",
  "uvicorn-worker>=0.3.0",
]
