name: Deploy Docs
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: write
  id-token: write
  pages: write
concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - name: Install latest PlantUML
        run: |
          sudo apt install -y default-jre graphviz
          sudo curl -fSLo /opt/plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar
          sudo tee /usr/bin/plantuml <<'EOF'
          #!/bin/sh
          java -jar /opt/plantuml.jar "$@"
          EOF
          sudo chmod 755 /usr/bin/plantuml
      - name: Install sphinx dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Upload the artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/
  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.upload.output.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
